commands:
  # Hora
  -command:
    input: que horas são?
    entity: time
    action: getTime
  -command:
    input: me diga as horas.
    entity: time
    action: getTime
  # Data
  -command:
    input: qual é a data de hoje?
    entity: time
    action: getDate
  -command:
    input: data de hoje.
    entity: time
    action: getDate
  #tempo
  -command:
    input: Previsão do tempo
    entity: weather
    action: getWeather
  -command:
    input: Como esta o clima?
    entity: weather
    action: getWeather
  #Open
  -command:
    input: Abrir google
    entity: open
    action: 
  -command:
    input: Abrir youtube
    entity: open
    action: 
  -command:
    input: Abrir vscode
    entity: open
    action: 
  